### ISSUE TITLE
올려주신 login 코드 사용에 대해 문의드립니다. 

### ISSUE THREAD

**Issue by leejin-yeong** [sn-spotchat/sproutchat#13]
login 코드를 이용해봤는데 제대로 실행이 되지 않습니다. 

현재 server 코드는 이렇습니다. 
https://github.com/sn-spotchat/sproutchat/blob/jinyoung/src/chat/Server.js
그리고 올려주신 login 코드를 약간 수정했습니다. 
https://github.com/sn-spotchat/sproutchat/blob/jinyoung/src/routes/Board/login_test.tsx

login 코드 안의 socket.on('login')이 실행되지 않아 server에도 socket.on('login')을 만들어봤더니 실행이 됩니다.
login 코드는 connect만 콘솔에 뜨고 login은 실행이 되지 않습니다.  어떤 문제인가요?

그리고 react와 server를 실행할때 vscode에서 npm start로 react를 실행시킨 뒤
cmd로 node src/chat/Server.js로 서버를 실행시키고 있습니다. 
이렇게 하는게 맞는지 문의드립니다.
그리고 connect 되는데 시간이 좀 걸리는 것 같은데(console에 connected가 나중에 뜹니다.) 원래 그런 건가요?

**Comment by arkist** [comment]
@leejin-yeong `socket.io`의 동작에 대한 이해가 먼저 필요해 보입니다 😅
https://github.com/socketio/socket.io/blob/master/examples/chat/index.js socket.io쪽 공식 데모 예제코드인데요, 
이 코드를 보고 동작을 분석해보세요. 
서버와 클라이언트간 메시지 통신이 어떻게 이루어 지는지 파악해보세요.

서버실행 부분은 `npm start`는 `package.json`의 `scripts`내에 선언된 명령을 실행하는 것 뿐이기 때문에 `node src/chat/Server.js` 또한 `start:socket` 등 별도로 선언해두고 호출해도 됩니다. 

그리고 현재 저장소에 있는 코드로는 포트가 중복되서 문제가 있는것 같은데요 (주석을 보니 3001로 변경하시려던 흔적이 보이긴 하는데)
포트를 다르게 할 경우 socket.io v3에서는 CORS 문제가 있을 수 있습니다. 이건 공식문서의 가이드를 참고해주세요
https://socket.io/docs/v3/migrating-from-2-x-to-3-0/index.html#CORS-handling

connect 자체는 서버에서 코드 로드 후에 -> 리액트 앱을 화면에 그려주고 -> 컴포넌트 트리를 순회하며 개별 컴포넌트의 생명주기 메소드가 실행된 후 connect가 되는거라 즉각적으로 반응하지 않을수는 있습니다. '시간이 좀 걸리는 것 같은데'에서 '좀'은 어느정도인가요? 몇초씩 된다면 문제가 있는것 같구요 🤔

**Comment by setosejin** [comment]
여전히 멘토님 코드와 싸움중(?)입니다.😤

서버와 클라이언트 간 통신은 다른 포트로 하여 완료된 상태이고, 
handleSubmit -> handelLogin -> socket.emit() -> socket.on 순으로 실행되는데
socket.emit()에 코드가 들어가지 않습니다.

정말 여러 코드를 읽어봤는데 서버 코드조차 typescript로 되어 있어야 하는지, 아니면 파일들의 위치가 문제가 되는지, socket과의 연결에서 import하지 않은 것이 있는지... 솔직히 문제가 되는 부분이 어느 지점인지 정확히 모르겠습니다.
이 부분에 대한 힌트를 얻을 수 있을까요??🙏🏻

**Comment by leejin-yeong** [comment]
cors option 설정하니까 해결된 것 같습니다. 또 관련 질문 있으면 열겠습니다!

**Comment by arkist** [comment]
@setosejin 말씀하신 사항이 cors 처리로 해결된게 맞나요?☺️ 에러 발생시에는 로그를 잘 읽어보면 힌트를 얻을 수 있습니다. 서버-클라이언트 통신 관련은 브라우저 개발자도구의 네트워크탭을 살펴보면 좋구요. 도움이 또 필요하면 말씀주세요~
