### ISSUE TITLE
소켓 통신 관련한 질문입니다

### ISSUE THREAD

**Issue by Nahyeon-Song** [sn-spotchat/sproutchat#26]
Login.js 파일에서 socket.emit을 통해 서버에 보낸 후 그 값을 Map.js에서 받아오려고 하는데 잘 되지 않아 질문드립니다. 
<Login.js>
![image](https://user-images.githubusercontent.com/62232757/100310100-d01a3600-2fef-11eb-9870-4fd73675471a.png)
<Server.js>
![image](https://user-images.githubusercontent.com/62232757/100310219-08217900-2ff0-11eb-8957-05ba3790748a.png)
<Map.js>
![image](https://user-images.githubusercontent.com/62232757/100310277-29826500-2ff0-11eb-8045-5b10d96a0592.png)

Login.js에서 socket.emit('userInfo', data.id)를 실행하여 서버의 socket.on으로 받고 다시 socket.emit을 하여 Map.js에서 componentDidMount 부분에서 data를 받아오려고 하는데 Map.js의 socket.on 자체가 실행이 안되는 것 같습니다. 어떻게 해결해야 할까요?

**Comment by arkist** [comment]
@Nahyeon-Song `setState` 아래 `console.log("i am " + data)` 부분도 실행이 되지 않나요?
만약 해당 구문은 실행이 되는데 그 아래 있는 `console.log("im " + this.state.userID)` 부분에서 `this.state.userID`가 원하는 값이 나오질 않는다면, 해당 부분을 원 의도대로 처리하려면 `componentDidUpdate`에서 제어해야 할 것입니다.
```jsx
componentDidUpdate(prevProps, prevState) {
  if (prevState.userID !== this.state.userId) {
    // 여기서 처리
  }
}
```
리액트에서는 상태를 두고 해당값의 변화에 반응해서(reactive) 동작이 수행되는 패러다임입니다. 이 부분을 다시 고민해보세요.

만약 해당케이스가 아니라면,, 서버쪽에서는 메시지를 받고 있는지부터 확인해봐야겠네요 👀

**Comment by Nahyeon-Song** [comment]
넵! 한번 해보겠습니다..!
