### ISSUE TITLE
React에서 jquery 관련 문법을 쓸 수 없나요?

### ISSUE THREAD

**Issue by setosejin** [sn-spotchat/sproutchat#29]
https://github.com/sn-spotchat/sproutchat/blob/sejin/src/chat/Chatting.tsx
위 코드에서 채팅을 나타내는 과정에서 발생한 문제입니다.

유저가 작성한 메시지가 socket.emit과 socket.on에는 잘 들어온 것을 확인해서 socket.on 안에서 아래와 같은 코드로 화면 상에 띄우려고 했습니다. 

> $chatLog.append(`<div className="myMsg msgEl"><span className="msg">${data.msg}</span></div>`)

@types/jquery와 jquery는 모두 설치되어있습니다.
하지만 이 부분이 잘 되지 않아서 혹시 다른 것을 추가로 설치해야 하는지, 아니면 아예 쓸 수 없는 것인지 알고싶습니다. 😟

**Comment by arkist** [comment]
@setosejin `$chatLog`이 전역으로 선언되어 있는데요, 이 경우 해당 선언은 *스크립트 로드 시점*에 즉시 실행되게 됩니다.
참조하고 있는 `div#chatLog`는 `<ChatForm/>`이 렌더해주고 있는데 이는 `$chatLog` 선언 이후이므로,
 `var $chatLog = $('#chatLog')` 구문이 실행되는 시점에는 해당 DOM 노드가 그려지기 이전이라서 참조되는 노드가 없습니다.
이는 해당 변수 선언 바로 아래 `console.log`를 찍어보면 확인할 수 있습니다.

해서 `<ChatForm/>`이 렌더된 이후 시점에 해당 DOM을 참조해야 하므로, 변수 선언을 `useEffect` 내애서 하면 의도하신대로 작동할 겁니다 :smile:

추가적으로 고민해 볼 문제: 그럼 `useEffect` 함수블럭이 실행되는 시점마다 `$chatLog`가 새롭게 선언하고 참조되는게 아닌가? -> 맞습니다.
이 문제는 다른 방식으로 해결할 수 있습니다. 관심이 가면 React의 `useEffect`, `useRef`에 대해 더 학습해 보고 고민해보세요~

**Comment by setosejin** [comment]
해결되었습니다! 감사합니당 :)
