### ISSUE TITLE
[질문] 리액트 프로젝트 통합 시 HTML파일을 컴포넌트 안에서 쓸 수 있나요?

### ISSUE THREAD

**Issue by setosejin** [sn-spotchat/sproutchat#8]
두 프로젝트를 통합하고 있습니다.
리액트 프로젝트 내 컴포넌트의 return에서 HTML로 쓴 파일을 읽고 싶은데 
확장자가 HTML인 파일은 지원하지 않는 것 같고, <div>는 읽히는 것 같지만 <script>를 못 읽어서
중요한 부분은 표시가 되지 않습니다. 
어떻게 하면 좋을까요?

**Comment by leejin-yeong** [comment]
올려주신 코드 확인해봤습니다. 프로젝트에 넣어서 실행해봤는데요.

loginForm은 실행이 되는데 handleLogin안의 socket.emit부터 안되는 것 같습니다.
확인해보면 안의 alert조차 띄우지 못합니다.

다른 socket.io를 사용하는 코드들을 보면 server와 client 코드를 나누고 
/*const express = require('express');
const app = express();
const server = require('http').Server(app);
const io = require('socket.io')(server);
const prot=process.env.PORT || 3005;
server.listen(prot, ()=>{console.log(`listening on prot ${prot}`)});*/

이런 코드가 필요하던데 올려주신 코드는 이 부분 없이도 되는 것인지 아니면 저희가 다시 적용해봐야하는 부분인가요?

**Comment by arkist** [comment]
@leejin-yeong 위에 공유드린 본 이슈 내의 코드들만 확인하고 구현한 내용이고, 서버쪽 코드는 당연히 존재할것이라 생각했습니다.
그것마저 제가 하면 프로젝트를 아예 제가 대신 구현해주는게 되어버리겠죠 😂 

본 이슈는 '기존의 HTML/script를 어떻게 리액트로 포팅할 수 있을까?' 에 대한 힌트를 얻기 위함이라고 생각되구요,
socket.io를 통한 채팅서버의 구현은 직접 해결하셔야 하는 내용이 되겠습니다 😇 찾아보신 내용을 토대로 직접 구현해보시고 그 과정에 또 궁금한 점은 질문주세요~

**Comment by leejin-yeong** [comment]
넵 서버 쪽 코드와 함께 적용해보겠습니다 감사합니다!
